package org.ap.summonerwar.constants;

/* This class was auto-generated by the JavaWriter */
public enum EElemType {

	_WATER ("Water"),
	_FIRE ("Fire"),
	_WIND ("Wind"),
	_LIGHT ("Light"),
	_DARK ("Dark"),
	;

	private String _name;

	private  EElemType(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EElemType getByName(String name) {
		for (EElemType value: EElemType.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
