package org.ap.summonerwar.constants;

/* This class was auto-generated by the JavaWriter */
public enum EPosType {

	_1 ("1"),
	_2 ("2"),
	_3 ("3"),
	_4 ("4"),
	_5 ("5"),
	_6 ("6"),
	;

	private String _name;

	private  EPosType(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EPosType getByName(String name) {
		for (EPosType value: EPosType.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
