package org.ap.summonerwar.constants;

/* This class was auto-generated by the JavaWriter */
public enum EStatType {

	_ATK ("Atk"),
	_ATK_FLAT ("AtkFlat"),
	_DEF ("Def"),
	_DEF_FLAT ("DefFlat"),
	_SPD ("Spd"),
	_CRATE ("Crate"),
	_CDMG ("Cdmg"),
	_RES ("Res"),
	_ACC ("Acc"),
	_HP ("Hp"),
	_HP_FLAT ("HpFlat"),
	;

	private String _name;

	private  EStatType(String name) {
		_name = name;
	}

	public String getName() {
		return _name;
	}

	public static EStatType getByName(String name) {
		for (EStatType value: EStatType.values()) {
			if (value.getName().equals(name)) {
				return value;
			}
		}
		return null;
	}

}
