import AppHelper from 'helpers/AppHelper'
import AuthHelper from 'helpers/AuthHelper'
import StatType from 'utils/constants/StatType'
import {Utils, BaseData}  from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class BuildMonsterConfigData extends BaseData {

	register(obj) {
		super.register(obj)

		this.statTypeValues = []
        for(var i = 0; i < StatType.VALUES.length; i++) {
            this.statTypeValues.push(StatType.VALUES[i].key)
        }

        this.obj.onClickShow = this.onClickShow.bind(this)

		this.obj.state = {
            statTypeValues: this.statTypeValues,
            requiredStatIsOpen: false,
            notationStatIsOpen: false,
            setsIsOpen: false 
        }
	}

	onClickShow(id) {
		if(id == 'requiredStat') {
			this.setState({requiredStatIsOpen: !this.getState('requiredStatIsOpen')})
		}
		else if( id == 'notationStat')
			this.setState({notationStatIsOpen: !this.getState('notationStatIsOpen')})
		else
			this.setState({setsIsOpen: !this.getState('setsIsOpen')})
	}

	unregister() {
	}

}

var BuildMonsterConfigDataObj = new BuildMonsterConfigData();
export default BuildMonsterConfigDataObj;
