import React from 'react';
import {RaterStar, Utils} from 'ap-react-bootstrap';
import RuneHelper from 'helpers/RuneHelper';
import AuthHelper from 'helpers/AuthHelper';
import Rune from 'components/lib/rune/Rune';

import './MonsterRunes.scss';

/* This class was auto-generated by the JavaScriptWriter */
class MonsterRunes extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		RuneHelper.register(this, this.buildData.bind(this))
		RuneHelper.getMonsterRunes(this.props.monster.id)
		this.setState({monster: this.props.monster})
	}

	componentWillReceiveProps(nextProps) {
		RuneHelper.getMonsterRunes(nextProps.monster.id)
		this.runes = RuneHelper.getData()
		this.setState({monster: nextProps.monster, runes: this.runes})
	}

	buildData() {
		this.runes = RuneHelper.getData()
		this.setState({runes: this.runes})
	}

	buildRune(rune) {
		return (<Rune key={rune.id} rune={rune}/>)
	}

	render() {
		return (
			<div className="sm-monster-runes">
				<div className="row sm-monster-rune-row">
					<div className="col-xs-12">
						<div className="col-xs-6">
							<img className="sm-monster-runes-img" src="assets/images/runes.png" />
						</div>
						<div className="col-xs-6">
							<div className="sm-monster-rune-set">
								<h4>Set Effect</h4>
								<ul>
									<li>
										<img src="assets/images/runes/Rune-Blade.png"/>
										<p className="">Blade</p>
									</li>
									<li>
										<img src="assets/images/runes/Rune-Energy.png"/>
										<p className="">Energy</p>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div className="col-xs-12">
						<div className="sm-monster-runes-list">
							{Utils.map(this.state.runes, this.buildRune)}
						</div>
					</div>
				</div>
			</div>
		);
	}

}
export default MonsterRunes;
