package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class BuildResultData {

	public Double eval;
	public String buildId;
	public String id;
	public String userId;

	public Double getEval() {
		return this.eval;
	}

	public void setEval(Double eval) {
		this.eval = eval;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
