package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class BuildData {

	public Integer runesLvl;
	public String name;
	public String state;
	public String id;
	public String userId;
	public Integer runesStars;

	public Integer getRunesLvl() {
		return this.runesLvl;
	}

	public void setRunesLvl(Integer runesLvl) {
		this.runesLvl = runesLvl;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getRunesStars() {
		return this.runesStars;
	}

	public void setRunesStars(Integer runesStars) {
		this.runesStars = runesStars;
	}

}
