package org.ap.summonerwar.storage;

import org.bson.Document;
import org.bson.conversions.Bson;
import org.ap.web.storage.Mongo;
import static com.mongodb.client.model.Filters.*;
import org.ap.web.internal.APWebException;
import java.util.List;
import java.util.ArrayList;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.result.DeleteResult;

/* This class was auto-generated by the JavaWriter */
public class BuildCollection {

	public static MongoCollection<Document> getCollection() throws APWebException {
		return Mongo.get().collection("build");
	}

	public static BuildData getById(String id) throws APWebException {
		Document document = getCollection().find(eq("id", id)).first();
		return fromDocument(document);
	}

	public static boolean deleteById(String id) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("id", id));
		return document != null;
	}

	public static List<BuildData> getAll() throws APWebException {
		FindIterable<Document> documents = getCollection().find();
		List<BuildData> result = new ArrayList<BuildData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static List<BuildData> get(Bson condition) throws APWebException {
		FindIterable<Document> documents = getCollection().find(condition);
		List<BuildData> result = new ArrayList<BuildData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static void create(BuildData data) throws APWebException {
		Document document = toDocument(data);
		getCollection().insertOne(document);
	}

	public static boolean update(BuildData data) throws APWebException {
		Document document = toDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean updateNull(BuildData data) throws APWebException {
		Document document = toNullDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean delete(BuildData data) throws APWebException {
		Document result = getCollection().findOneAndDelete(eq("id", data.getId()));
		return result != null;
	}

	public static long deleteMany(Bson condition) throws APWebException {
		DeleteResult result = getCollection().deleteMany(condition);
		return result.getDeletedCount();
	}

	public static long drop() throws APWebException {
		long result = getCollection().count();
		getCollection().drop();
		return result;
	}

	public static BuildData fromDocument(Document document) {
		if(document == null) {
			return null;
		}
		BuildData data = new BuildData();
		data.name = document.getString("name");
		data.id = document.getString("id");
		data.userId = document.getString("userId");
		return data;
	}

	public static Document toDocument(BuildData build) {
		Document document = new Document();
		if (build.name != null)
			document.append("name", build.name);
		if (build.id != null)
			document.append("id", build.id);
		if (build.userId != null)
			document.append("userId", build.userId);
		return document;
	}

	public static Document toNullDocument(BuildData build) {
		Document document = new Document();
		document.append("name", build.name);
		document.append("id", build.id);
		document.append("userId", build.userId);
		return document;
	}

}
