package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class BuildData {

	public String name;
	public String id;
	public String userId;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
