package org.ap.summonerwar.storage;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class BuildResultData {

	public String buildId;
	public String id;
	public List<Integer> creationDate;
	public String userId;

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<Integer> getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(List<Integer> creationDate) {
		this.creationDate = creationDate;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
