package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class MonsterConfigData {

	public Integer requiredDef;
	public Integer notationSpd;
	public Integer requiredAcc;
	public Integer notationHp;
	public Integer requiredHpFlat;
	public Integer requiredDefFlat;
	public Integer requiredAtkFlat;
	public Integer requiredCrate;
	public String monsterId;
	public Integer notationHpFlat;
	public String id;
	public Integer requiredAtk;
	public Integer requiredCdmg;
	public Integer notationCdmg;
	public Integer notationAcc;
	public Integer notationDef;
	public String set3;
	public Integer requiredRes;
	public String set2;
	public String buildId;
	public Integer requiredSpd;
	public String userId;
	public Integer notationDefFlat;
	public Integer requiredHp;
	public Integer notationAtkFlat;
	public Integer notationCrate;
	public Integer notationAtk;
	public String set1;
	public Integer notationRes;

	public Integer getRequiredDef() {
		return this.requiredDef;
	}

	public void setRequiredDef(Integer requiredDef) {
		this.requiredDef = requiredDef;
	}

	public Integer getNotationSpd() {
		return this.notationSpd;
	}

	public void setNotationSpd(Integer notationSpd) {
		this.notationSpd = notationSpd;
	}

	public Integer getRequiredAcc() {
		return this.requiredAcc;
	}

	public void setRequiredAcc(Integer requiredAcc) {
		this.requiredAcc = requiredAcc;
	}

	public Integer getNotationHp() {
		return this.notationHp;
	}

	public void setNotationHp(Integer notationHp) {
		this.notationHp = notationHp;
	}

	public Integer getRequiredHpFlat() {
		return this.requiredHpFlat;
	}

	public void setRequiredHpFlat(Integer requiredHpFlat) {
		this.requiredHpFlat = requiredHpFlat;
	}

	public Integer getRequiredDefFlat() {
		return this.requiredDefFlat;
	}

	public void setRequiredDefFlat(Integer requiredDefFlat) {
		this.requiredDefFlat = requiredDefFlat;
	}

	public Integer getRequiredAtkFlat() {
		return this.requiredAtkFlat;
	}

	public void setRequiredAtkFlat(Integer requiredAtkFlat) {
		this.requiredAtkFlat = requiredAtkFlat;
	}

	public Integer getRequiredCrate() {
		return this.requiredCrate;
	}

	public void setRequiredCrate(Integer requiredCrate) {
		this.requiredCrate = requiredCrate;
	}

	public String getMonsterId() {
		return this.monsterId;
	}

	public void setMonsterId(String monsterId) {
		this.monsterId = monsterId;
	}

	public Integer getNotationHpFlat() {
		return this.notationHpFlat;
	}

	public void setNotationHpFlat(Integer notationHpFlat) {
		this.notationHpFlat = notationHpFlat;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getRequiredAtk() {
		return this.requiredAtk;
	}

	public void setRequiredAtk(Integer requiredAtk) {
		this.requiredAtk = requiredAtk;
	}

	public Integer getRequiredCdmg() {
		return this.requiredCdmg;
	}

	public void setRequiredCdmg(Integer requiredCdmg) {
		this.requiredCdmg = requiredCdmg;
	}

	public Integer getNotationCdmg() {
		return this.notationCdmg;
	}

	public void setNotationCdmg(Integer notationCdmg) {
		this.notationCdmg = notationCdmg;
	}

	public Integer getNotationAcc() {
		return this.notationAcc;
	}

	public void setNotationAcc(Integer notationAcc) {
		this.notationAcc = notationAcc;
	}

	public Integer getNotationDef() {
		return this.notationDef;
	}

	public void setNotationDef(Integer notationDef) {
		this.notationDef = notationDef;
	}

	public String getSet3() {
		return this.set3;
	}

	public void setSet3(String set3) {
		this.set3 = set3;
	}

	public Integer getRequiredRes() {
		return this.requiredRes;
	}

	public void setRequiredRes(Integer requiredRes) {
		this.requiredRes = requiredRes;
	}

	public String getSet2() {
		return this.set2;
	}

	public void setSet2(String set2) {
		this.set2 = set2;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public Integer getRequiredSpd() {
		return this.requiredSpd;
	}

	public void setRequiredSpd(Integer requiredSpd) {
		this.requiredSpd = requiredSpd;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getNotationDefFlat() {
		return this.notationDefFlat;
	}

	public void setNotationDefFlat(Integer notationDefFlat) {
		this.notationDefFlat = notationDefFlat;
	}

	public Integer getRequiredHp() {
		return this.requiredHp;
	}

	public void setRequiredHp(Integer requiredHp) {
		this.requiredHp = requiredHp;
	}

	public Integer getNotationAtkFlat() {
		return this.notationAtkFlat;
	}

	public void setNotationAtkFlat(Integer notationAtkFlat) {
		this.notationAtkFlat = notationAtkFlat;
	}

	public Integer getNotationCrate() {
		return this.notationCrate;
	}

	public void setNotationCrate(Integer notationCrate) {
		this.notationCrate = notationCrate;
	}

	public Integer getNotationAtk() {
		return this.notationAtk;
	}

	public void setNotationAtk(Integer notationAtk) {
		this.notationAtk = notationAtk;
	}

	public String getSet1() {
		return this.set1;
	}

	public void setSet1(String set1) {
		this.set1 = set1;
	}

	public Integer getNotationRes() {
		return this.notationRes;
	}

	public void setNotationRes(Integer notationRes) {
		this.notationRes = notationRes;
	}

}
