package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class MonsterData {

	public Integer acc;
	public Integer res;
	public Integer lvl;
	public String role;
	public Integer star;
	public Boolean isAwaked;
	public Integer def;
	public Integer spd;
	public Integer hp;
	public Integer crate;
	public String elemType;
	public Integer cdmg;
	public String name;
	public Integer xp;
	public Integer atk;
	public String id;
	public String user;

	public Integer getAcc() {
		return this.acc;
	}

	public void setAcc(Integer acc) {
		this.acc = acc;
	}

	public Integer getRes() {
		return this.res;
	}

	public void setRes(Integer res) {
		this.res = res;
	}

	public Integer getLvl() {
		return this.lvl;
	}

	public void setLvl(Integer lvl) {
		this.lvl = lvl;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	public Boolean getIsAwaked() {
		return this.isAwaked;
	}

	public void setIsAwaked(Boolean isAwaked) {
		this.isAwaked = isAwaked;
	}

	public Integer getDef() {
		return this.def;
	}

	public void setDef(Integer def) {
		this.def = def;
	}

	public Integer getSpd() {
		return this.spd;
	}

	public void setSpd(Integer spd) {
		this.spd = spd;
	}

	public Integer getHp() {
		return this.hp;
	}

	public void setHp(Integer hp) {
		this.hp = hp;
	}

	public Integer getCrate() {
		return this.crate;
	}

	public void setCrate(Integer crate) {
		this.crate = crate;
	}

	public String getElemType() {
		return this.elemType;
	}

	public void setElemType(String elemType) {
		this.elemType = elemType;
	}

	public Integer getCdmg() {
		return this.cdmg;
	}

	public void setCdmg(Integer cdmg) {
		this.cdmg = cdmg;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getXp() {
		return this.xp;
	}

	public void setXp(Integer xp) {
		this.xp = xp;
	}

	public Integer getAtk() {
		return this.atk;
	}

	public void setAtk(Integer atk) {
		this.atk = atk;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
