package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class MonsterResultData {

	public Integer acc;
	public String rune6;
	public Integer res;
	public String rune3;
	public Integer def;
	public String rune2;
	public String rune5;
	public Integer spd;
	public String rune4;
	public Integer hp;
	public String rune1;
	public Integer crate;
	public String userId;
	public String teamResultId;
	public Integer cdmg;
	public Integer atk;
	public String id;
	public String monsterConfigId;

	public Integer getAcc() {
		return this.acc;
	}

	public void setAcc(Integer acc) {
		this.acc = acc;
	}

	public String getRune6() {
		return this.rune6;
	}

	public void setRune6(String rune6) {
		this.rune6 = rune6;
	}

	public Integer getRes() {
		return this.res;
	}

	public void setRes(Integer res) {
		this.res = res;
	}

	public String getRune3() {
		return this.rune3;
	}

	public void setRune3(String rune3) {
		this.rune3 = rune3;
	}

	public Integer getDef() {
		return this.def;
	}

	public void setDef(Integer def) {
		this.def = def;
	}

	public String getRune2() {
		return this.rune2;
	}

	public void setRune2(String rune2) {
		this.rune2 = rune2;
	}

	public String getRune5() {
		return this.rune5;
	}

	public void setRune5(String rune5) {
		this.rune5 = rune5;
	}

	public Integer getSpd() {
		return this.spd;
	}

	public void setSpd(Integer spd) {
		this.spd = spd;
	}

	public String getRune4() {
		return this.rune4;
	}

	public void setRune4(String rune4) {
		this.rune4 = rune4;
	}

	public Integer getHp() {
		return this.hp;
	}

	public void setHp(Integer hp) {
		this.hp = hp;
	}

	public String getRune1() {
		return this.rune1;
	}

	public void setRune1(String rune1) {
		this.rune1 = rune1;
	}

	public Integer getCrate() {
		return this.crate;
	}

	public void setCrate(Integer crate) {
		this.crate = crate;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getTeamResultId() {
		return this.teamResultId;
	}

	public void setTeamResultId(String teamResultId) {
		this.teamResultId = teamResultId;
	}

	public Integer getCdmg() {
		return this.cdmg;
	}

	public void setCdmg(Integer cdmg) {
		this.cdmg = cdmg;
	}

	public Integer getAtk() {
		return this.atk;
	}

	public void setAtk(Integer atk) {
		this.atk = atk;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMonsterConfigId() {
		return this.monsterConfigId;
	}

	public void setMonsterConfigId(String monsterConfigId) {
		this.monsterConfigId = monsterConfigId;
	}

}
