package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class RuneData {

	public Integer lvl;
	public String set;
	public String stat4Type;
	public Integer star;
	public String stat2Type;
	public Integer statSub;
	public Integer statMain;
	public Integer stat4;
	public String userId;
	public String stat3Type;
	public Integer stat2;
	public String pos;
	public Integer stat3;
	public String statSubType;
	public String monsterId;
	public Integer stat1;
	public String stat1Type;
	public String statMainType;
	public String id;
	public Long uniqueId;

	public Integer getLvl() {
		return this.lvl;
	}

	public void setLvl(Integer lvl) {
		this.lvl = lvl;
	}

	public String getSet() {
		return this.set;
	}

	public void setSet(String set) {
		this.set = set;
	}

	public String getStat4Type() {
		return this.stat4Type;
	}

	public void setStat4Type(String stat4Type) {
		this.stat4Type = stat4Type;
	}

	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	public String getStat2Type() {
		return this.stat2Type;
	}

	public void setStat2Type(String stat2Type) {
		this.stat2Type = stat2Type;
	}

	public Integer getStatSub() {
		return this.statSub;
	}

	public void setStatSub(Integer statSub) {
		this.statSub = statSub;
	}

	public Integer getStatMain() {
		return this.statMain;
	}

	public void setStatMain(Integer statMain) {
		this.statMain = statMain;
	}

	public Integer getStat4() {
		return this.stat4;
	}

	public void setStat4(Integer stat4) {
		this.stat4 = stat4;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getStat3Type() {
		return this.stat3Type;
	}

	public void setStat3Type(String stat3Type) {
		this.stat3Type = stat3Type;
	}

	public Integer getStat2() {
		return this.stat2;
	}

	public void setStat2(Integer stat2) {
		this.stat2 = stat2;
	}

	public String getPos() {
		return this.pos;
	}

	public void setPos(String pos) {
		this.pos = pos;
	}

	public Integer getStat3() {
		return this.stat3;
	}

	public void setStat3(Integer stat3) {
		this.stat3 = stat3;
	}

	public String getStatSubType() {
		return this.statSubType;
	}

	public void setStatSubType(String statSubType) {
		this.statSubType = statSubType;
	}

	public String getMonsterId() {
		return this.monsterId;
	}

	public void setMonsterId(String monsterId) {
		this.monsterId = monsterId;
	}

	public Integer getStat1() {
		return this.stat1;
	}

	public void setStat1(Integer stat1) {
		this.stat1 = stat1;
	}

	public String getStat1Type() {
		return this.stat1Type;
	}

	public void setStat1Type(String stat1Type) {
		this.stat1Type = stat1Type;
	}

	public String getStatMainType() {
		return this.statMainType;
	}

	public void setStatMainType(String statMainType) {
		this.statMainType = statMainType;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(Long uniqueId) {
		this.uniqueId = uniqueId;
	}

}
