package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class TeamResultData {

	public String buildResultId;
	public Double eval;
	public String id;
	public String userId;

	public String getBuildResultId() {
		return this.buildResultId;
	}

	public void setBuildResultId(String buildResultId) {
		this.buildResultId = buildResultId;
	}

	public Double getEval() {
		return this.eval;
	}

	public void setEval(Double eval) {
		this.eval = eval;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
