package org.ap.summonerwar.storage;

import org.bson.Document;
import org.bson.conversions.Bson;
import org.ap.web.storage.Mongo;
import static com.mongodb.client.model.Filters.*;
import org.ap.web.internal.APWebException;
import java.util.List;
import java.util.ArrayList;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.result.DeleteResult;

/* This class was auto-generated by the JavaWriter */
public class TeamResultCollection {

	public static MongoCollection<Document> getCollection() throws APWebException {
		return Mongo.get().collection("teamResult");
	}

	public static TeamResultData getById(String id) throws APWebException {
		Document document = getCollection().find(eq("id", id)).first();
		return fromDocument(document);
	}

	public static boolean deleteById(String id) throws APWebException {
		Document document = getCollection().findOneAndDelete(eq("id", id));
		return document != null;
	}

	public static List<TeamResultData> getAll() throws APWebException {
		FindIterable<Document> documents = getCollection().find();
		List<TeamResultData> result = new ArrayList<TeamResultData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static List<TeamResultData> get(Bson condition) throws APWebException {
		FindIterable<Document> documents = getCollection().find(condition);
		List<TeamResultData> result = new ArrayList<TeamResultData>();
		for (Document document: documents){
			result.add(fromDocument(document));
		}
		return result;
	}

	public static void create(TeamResultData data) throws APWebException {
		Document document = toDocument(data);
		getCollection().insertOne(document);
	}

	public static boolean update(TeamResultData data) throws APWebException {
		Document document = toDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean updateNull(TeamResultData data) throws APWebException {
		Document document = toNullDocument(data);
		Document result = getCollection().findOneAndUpdate(eq("id", data.getId()), new Document("$set", document));
		return result != null;
	}

	public static boolean delete(TeamResultData data) throws APWebException {
		Document result = getCollection().findOneAndDelete(eq("id", data.getId()));
		return result != null;
	}

	public static long deleteMany(Bson condition) throws APWebException {
		DeleteResult result = getCollection().deleteMany(condition);
		return result.getDeletedCount();
	}

	public static long drop() throws APWebException {
		long result = getCollection().count();
		getCollection().drop();
		return result;
	}

	public static TeamResultData fromDocument(Document document) {
		if(document == null) {
			return null;
		}
		TeamResultData data = new TeamResultData();
		data.buildResultId = document.getString("buildResultId");
		data.eval = document.getDouble("eval");
		data.id = document.getString("id");
		data.userId = document.getString("userId");
		return data;
	}

	public static Document toDocument(TeamResultData teamResult) {
		Document document = new Document();
		if (teamResult.buildResultId != null)
			document.append("buildResultId", teamResult.buildResultId);
		if (teamResult.eval != null)
			document.append("eval", teamResult.eval);
		if (teamResult.id != null)
			document.append("id", teamResult.id);
		if (teamResult.userId != null)
			document.append("userId", teamResult.userId);
		return document;
	}

	public static Document toNullDocument(TeamResultData teamResult) {
		Document document = new Document();
		document.append("buildResultId", teamResult.buildResultId);
		document.append("eval", teamResult.eval);
		document.append("id", teamResult.id);
		document.append("userId", teamResult.userId);
		return document;
	}

}
