package org.ap.summonerwar.storage;

/* This class was auto-generated by the JavaWriter */
public class UserData {

	public String authId;
	public Long lastImport;
	public String id;

	public String getAuthId() {
		return this.authId;
	}

	public void setAuthId(String authId) {
		this.authId = authId;
	}

	public Long getLastImport() {
		return this.lastImport;
	}

	public void setLastImport(Long lastImport) {
		this.lastImport = lastImport;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
