package org.ap.summonerwar.storage;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class UserData {

	public String authId;
	public List<Integer> lastImport;
	public String id;

	public String getAuthId() {
		return this.authId;
	}

	public void setAuthId(String authId) {
		this.authId = authId;
	}

	public List<Integer> getLastImport() {
		return this.lastImport;
	}

	public void setLastImport(List<Integer> lastImport) {
		this.lastImport = lastImport;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
