import AppHelper from 'helpers/AppHelper';

/* This class was auto-generated by the JavaScriptWriter */
class ProfileData {

	register(obj) {
		this.obj = obj
	}

	unregister() {
	}

}
var ProfileObj = new ProfileData();
export default ProfileObj;
