import React from 'react';
import AppData from 'components/AppData';
import './App.scss';

/* This class was auto-generated by the JavaScriptWriter */
class App extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		AppData.register(this)
	}

	componentWillUnmount() {
		AppData.unregister()
	}

	render() {
		return (
			<div className='ap-app'>

				<nav className="sm-sidebar">
					<div className="sm-sidebar-logo-content">
						<a href="/" className="">
							<img alt="Summoners War" className="sm-sidebar-logo" src="assets/images/logo.png"/>
						</a>
					</div>
		    		<div className="sm-sidebar-profile">
		    			<a href="profile">
		    				<img alt="Summoners War" className="sm-sidebar-profile-img" src="assets/images/monster.jpg"/>
		    				PseudoName
		    			</a>
		    		</div>
					<ul>
						<li><a href="import">Import</a></li>
				        <li><a href="monsters">Monsters</a></li>
				        <li><a href="runes">Runes</a></li>
				        <li><a href="builds">Builds</a></li>
			      	</ul>
				</nav>

				<header></header>
				<section className={"sm-section"}>
					<div className={"container sm-container"}>
						{this.props.children}
					</div>
				</section>
				<footer>
					<div className={"sm-footer"}>
					  	<p className={"sm-copyright"}>Copyright @ 2017 Com2Us. This is a fan site, we are not affiliated with Com2Us.</p>
					</div>
				</footer>
			</div>
		);
	}

}
export default App;
