import AppHelper from 'helpers/AppHelper';
import AuthHelper from 'helpers/AuthHelper';
import UserHelper from 'helpers/UserHelper';
import { BaseData, Utils } from 'ap-react-bootstrap'

let PAGES = {
    import: "import",
    monsters: "monsters",
    runes: "runes",
    builds: "builds"
}

/* This class was auto-generated by the JavaScriptWriter */
class AppData extends BaseData {

	register(obj) {
		super.register(obj)

		this.obj.onClickHome = this.onClickHome
		this.obj.onClickProfile = this.onClickProfile

		Utils.forEach(PAGES, function(page) {
			this.obj[page] = this.onClickPage.bind(this, PAGES[page])
		}.bind(this))

		this.obj.state = {
			username: 'Homunculus',
			isLogged: false
		}

		UserHelper.register(this, this.buildDataUser.bind(this))
		if(AuthHelper.getEntityId())
			UserHelper.getUser(AuthHelper.getEntityId())
	}

	unregister() {
		UserHelper.unregister(this)
	}

	buildDataUser() {
        let username = UserHelper.getData(AuthHelper.getEntityId() + '/username')
		this.setState({
            username: username || 'Homunculus',
            isLogged: true
        })
	}

	onClickHome() {
		AppHelper.navigate('/');
	}

	onClickProfile() {
		AppHelper.navigate('/profile');
	}

	onClickPage(page) {
		this.obj.setState({activePage: page})
		AppHelper.navigate('/' + page);
	}

}
var AppObj = new AppData();
AppObj.PAGES = PAGES
export default AppObj;
