import { Validators } from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class BuildResultFields {

	static get BUILD_ID() {
		return _BUILD_ID
	}

	static get ID() {
		return _ID
	}

	static get CREATION_DATE() {
		return _CREATION_DATE
	}

	static get USER_ID() {
		return _USER_ID
	}

	static get VALUES() {
		return [
			_BUILD_ID,
			_ID,
			_CREATION_DATE,
			_USER_ID,
		]
	}

	static get(id) {
		for (let i = 0 ; i < BuildResultFields.VALUES.length ; i++) {
			if (BuildResultFields.VALUES[i].key === id) {
				return BuildResultFields.VALUES[i]
			}
		}
	}

}
let _BUILD_ID = {
	key: 'buildId',
	type: 'string',
}
let _ID = {
	key: 'id',
	type: 'string',
}
let _CREATION_DATE = {
	key: 'creationDate',
	type: 'number',
}
let _USER_ID = {
	key: 'userId',
	type: 'string',
}
export default BuildResultFields
