import React from 'react'
import BuildsData from 'components/builds/BuildsData'
import BuildMonsterConfig from 'components-lib/buildMonsterConfig/BuildMonsterConfig'
import BuildsList from 'components-lib/buildsList/BuildsList'
import {Utils}  from 'ap-react-bootstrap'

import './Builds.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Builds extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		BuildsData.register(this)
	}

	componentWillUnmount() {
		BuildsData.unregister()
	}

	_buildMonstersConfig(monsterConfig) {
		if(monsterConfig)
			return (<BuildMonsterConfig key={monsterConfig.id} monsterConfig={monsterConfig}/>)
	}

	render() {
		return (
			<div className='ap-builds'>
				<div className="row">
					<div className="col-xs-12 col-sm-2">
						 <BuildsList builds={this.state.builds} onClickBuild={this.state.onClickBuild}/>
					</div>
					<div className="col-xs-10 col-sm-10">
						<div className="sm-sheet sm-builds-monsters">
							{Utils.map(this.state.monstersConfig, this._buildMonstersConfig)}
							<div className="sm-builds-monster-add1">
								<i className="glyphicon glyphicon-plus-sign sm-builds-monster-add" onClick={this.onClickAddMonsterConfig.bind(this)}></i>
							</div>
						</div>
						<div className="sm-sheet sm-sheet-top sm-builds-infos">
							<label className="sm-label">Build Name</label>
							<input className="sm-input" type="text" value={this.state.build.name}/>
							<label className="sm-label">Status</label>
							<input className="sm-input" type="text" value={this.state.build.state} disabled={true}/>
							<button className="sm-button">Save</button>
							<button className="sm-button sm-builds-infos-build">Build</button>
						</div>
					</div>
				</div>
			</div>
		);
	}

}
export default Builds;
