import AppHelper from 'helpers/AppHelper';
import AuthHelper from 'helpers/AuthHelper';
import BuildHelper from 'helpers/BuildHelper';
import StatType from 'utils/constants/StatType'
import {Utils, BaseData}  from 'ap-react-bootstrap'


/* This class was auto-generated by the JavaScriptWriter */
class BuildsData extends BaseData {

	register(obj) {
		if(!AuthHelper.getEntityId()) {
            AppHelper.navigate("/")
        }
		super.register(obj)

		this.obj.onClickAddMonsterConfig = this.onClickAddMonsterConfig.bind(this)

		this.obj.state = {
            build: {}
        }

        AppHelper.register('/currentBuild', this, this.onBuildChange.bind(this));
	}

	onBuildChange() {
        let build = AppHelper.getData('/currentBuild')
        this.setState({ build: build})
    }


	onClickAddMonsterConfig() {
		console.log("ADD")
	}

	unregister() {
		AppHelper.unregister(this)
	}
}
var BuildsObj = new BuildsData();
export default BuildsObj;
