import React from 'react';
import BuildsData from 'components/builds/BuildsData';

import {Utils}  from 'ap-react-bootstrap'

import './Builds.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Builds extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		BuildsData.register(this)
	}

	componentWillUnmount() {
		BuildsData.unregister()
	}

	_buildBuild(build) {
		return (
			<li key={build.id}>
				<div className="sm-build"><span>{build.name}</span></div>
			</li>
		)
	}

	render() {
		return (
			<div className='ap-builds'>
				<div className="row">
					<div className="col-xs-2">
						 <div className="sm-sheet sm-builds-list">
						 	<ul>
						 		{ Utils.map(this.state.builds, this._buildBuild.bind(this))}
						 		<li>
									<div className="sm-build">
										<i className="glyphicon glyphicon-plus-sign sm-build-add"></i>
									</div>
								</li>
						 	</ul>
						 </div>
						 <div className="sm-sheet sm-sheet-top sm-builds-infos">
							 <label className="sm-label">Status</label>
							 <input className="sm-input" type="text" value="Optimized" disabled={true}/>
						 </div>
					</div>
					<div className="col-xs-10">
						<div className="sm-sheet sm-builds-monsters">
							MonstersConfig
						</div>
					</div>
				</div>
			</div>
		);
	}

}
export default Builds;
