import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
class BuildResultHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/buildResult', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getBuildresult(buildResultId) {
		return Dispatcher.issue('GET_BUILDRESULT', {token: AuthHelper.getToken(), buildResultId: buildResultId});
	}

	postBuildresult(data) {
		return Dispatcher.issue('POST_BUILDRESULT', {token: AuthHelper.getToken(), data: data});
	}

	putBuildresult(data) {
		return Dispatcher.issue('PUT_BUILDRESULT', {token: AuthHelper.getToken(), buildResultId: data.id, data: data});
	}

	deleteBuildresult(buildResultId) {
		return Dispatcher.issue('DELETE_BUILDRESULT', {token: AuthHelper.getToken(), buildResultId: buildResultId});
	}

	getUserBuildresult(userId) {
		return Dispatcher.issue('GET_USER_BUILDRESULT', {token: AuthHelper.getToken(), userId: userId});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/buildResult' + (id ? '/' + id : ''));
	}

}
var BuildResultObj = new BuildResultHelper()
export default BuildResultObj
