import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
class DefaultHelper {

	postBuildDo(data) {
		return Dispatcher.issue('POST_BUILD_DO', {token: AuthHelper.getToken(), data: data});
	}

	postUserImport(data) {
		return Dispatcher.issue('POST_USER_IMPORT', {token: AuthHelper.getToken(), data: data});
	}

}
var DefaultObj = new DefaultHelper()
export default DefaultObj
