import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
class MonsterConfigHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/monsterConfig', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/monsterConfig' + (id ? '/' + id : ''));
	}

}
var MonsterConfigObj = new MonsterConfigHelper()
export default MonsterConfigObj
