import { Dispatcher, StoreRegistry } from 'ap-flux';
import AuthHelper from 'helpers/AuthHelper';

/* This class was auto-generated by the JavaScriptWriter */
class MonsterHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/monster', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getMonsters() {
		return Dispatcher.issue('GET_MONSTERS', {token: AuthHelper.getToken()});
	}

	postMonster(data) {
		return Dispatcher.issue('POST_MONSTER', {token: AuthHelper.getToken(), data: data});
	}

	getMonster(id) {
		return Dispatcher.issue('GET_MONSTER', {token: AuthHelper.getToken(), id: id});
	}

	putMonster(data) {
		return Dispatcher.issue('PUT_MONSTER', {token: AuthHelper.getToken(), id: data.id, data: data});
	}

	deleteMonster(id) {
		return Dispatcher.issue('DELETE_MONSTER', {token: AuthHelper.getToken(), id: id});
	}

	getUserMonsters(user) {
		return Dispatcher.issue('GET_USER_MONSTERS', {token: AuthHelper.getToken(), user: user});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/monster' + (id ? '/' + id : ''));
	}

}
var MonsterObj = new MonsterHelper();
export default MonsterObj;
