import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
class MonsterResultHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/monsterResult', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getMonsterresult(monsterResultId) {
		return Dispatcher.issue('GET_MONSTERRESULT', {token: AuthHelper.getToken(), monsterResultId: monsterResultId});
	}

	postMonsterresult(data) {
		return Dispatcher.issue('POST_MONSTERRESULT', {token: AuthHelper.getToken(), data: data});
	}

	putMonsterresult(data) {
		return Dispatcher.issue('PUT_MONSTERRESULT', {token: AuthHelper.getToken(), monsterResultId: data.id, data: data});
	}

	deleteMonsterresult(monsterResultId) {
		return Dispatcher.issue('DELETE_MONSTERRESULT', {token: AuthHelper.getToken(), monsterResultId: monsterResultId});
	}

	getUserMonsterresult(userId) {
		return Dispatcher.issue('GET_USER_MONSTERRESULT', {token: AuthHelper.getToken(), userId: userId});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/monsterResult' + (id ? '/' + id : ''));
	}

}
var MonsterResultObj = new MonsterResultHelper()
export default MonsterResultObj
