import { Dispatcher, StoreRegistry } from 'ap-flux'
import AuthHelper from 'helpers/AuthHelper'

/* This class was auto-generated by the JavaScriptWriter */
class MonsterConfigHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/monsterConfig', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getMonstersconfig(monsterConfigId) {
		return Dispatcher.issue('GET_MONSTERSCONFIG', {token: AuthHelper.getToken(), monsterConfigId: monsterConfigId});
	}

	postMonstersconfig(data) {
		return Dispatcher.issue('POST_MONSTERSCONFIG', {token: AuthHelper.getToken(), data: data});
	}

	putMonstersconfig(data) {
		return Dispatcher.issue('PUT_MONSTERSCONFIG', {token: AuthHelper.getToken(), monsterConfigId: data.monsterConfigId, data: data});
	}

	deleteMonstersconfig(monsterConfigId) {
		return Dispatcher.issue('DELETE_MONSTERSCONFIG', {token: AuthHelper.getToken(), monsterConfigId: monsterConfigId});
	}

	getBuildMonstersconfig(buildId) {
		return Dispatcher.issue('GET_BUILD_MONSTERSCONFIG', {token: AuthHelper.getToken(), buildId: buildId});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/monsterConfig' + (id ? '/' + id : ''));
	}

}
var MonsterConfigObj = new MonsterConfigHelper()
export default MonsterConfigObj
