import { Dispatcher, StoreRegistry } from 'ap-flux';
import AuthHelper from 'helpers/AuthHelper';

/* This class was auto-generated by the JavaScriptWriter */
class MonsterHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/monster', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getMonsters() {
		return Dispatcher.issue('GET_MONSTERS', {token: AuthHelper.getToken()});
	}

	postMonster(data) {
		return Dispatcher.issue('POST_MONSTER', {token: AuthHelper.getToken(), data: data});
	}

	getMonster(monsterId) {
		return Dispatcher.issue('GET_MONSTER', {token: AuthHelper.getToken(), monsterId: monsterId});
	}

	putMonster(data) {
		return Dispatcher.issue('PUT_MONSTER', {token: AuthHelper.getToken(), monsterId: data.monsterId, data: data});
	}

	deleteMonster(monsterId) {
		return Dispatcher.issue('DELETE_MONSTER', {token: AuthHelper.getToken(), monsterId: monsterId});
	}

	getUserMonsters(userId) {
		return Dispatcher.issue('GET_USER_MONSTERS', {token: AuthHelper.getToken(), userId: userId});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/monster' + (id ? '/' + id : ''));
	}

}
var MonsterObj = new MonsterHelper();
export default MonsterObj;
