import { Dispatcher, StoreRegistry } from 'ap-flux';
import AuthHelper from 'helpers/AuthHelper';

/* This class was auto-generated by the JavaScriptWriter */
class RuneHelper {

	register(obj, callback) {
		StoreRegistry.register('REST_STORE/rune', obj, callback);
	}

	unregister(obj) {
		StoreRegistry.unregister('REST_STORE', obj);
	}

	getRunes() {
		return Dispatcher.issue('GET_RUNES', {token: AuthHelper.getToken()});
	}

	postRune(data) {
		return Dispatcher.issue('POST_RUNE', {token: AuthHelper.getToken(), data: data});
	}

	getRune(id) {
		return Dispatcher.issue('GET_RUNE', {token: AuthHelper.getToken(), id: id});
	}

	putRune(data) {
		return Dispatcher.issue('PUT_RUNE', {token: AuthHelper.getToken(), id: data.id, data: data});
	}

	deleteRune(id) {
		return Dispatcher.issue('DELETE_RUNE', {token: AuthHelper.getToken(), id: id});
	}

	getMonsterMonsters(monster) {
		return Dispatcher.issue('GET_MONSTER_MONSTERS', {token: AuthHelper.getToken(), monster: monster});
	}

	getUserRunes(user) {
		return Dispatcher.issue('GET_USER_RUNES', {token: AuthHelper.getToken(), user: user});
	}

	getData(id) {
		return StoreRegistry.getStore('REST_STORE').getData('/rune' + (id ? '/' + id : ''));
	}

}
var RuneObj = new RuneHelper();
export default RuneObj;
