import AppHelper from 'helpers/AppHelper';

/* This class was auto-generated by the JavaScriptWriter */
class ImportData {

	register(obj) {
		this.obj = obj
	}

	unregister() {
	}

}
var ImportObj = new ImportData();
export default ImportObj;
