import React from 'react';
import ImportData from 'components/import/ImportData';
import './Import.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Import extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		ImportData.register(this)
	}

	componentWillUnmount() {
		ImportData.unregister()
	}

	render() {
		return (
			<div className='ap-import'>
				<div className="row">
					<div className="col-xs-12">
						<h3 className="sm-import-title">Import your Json File</h3>
					</div>
				</div>
				<div className="row">
					<div className="col-xs-12 col-sm-6">
						<div className="sm-upload">
							<div className="sm-sheet sm-sheet-mid">
								<div className="sm-content sm-upload">
									<label htmlFor="file-upload" className="sm-label sm-upload-label">
									    {this.state.upload}
									</label>
									<input id="file-upload" type="file" ref={(c) => this.state.fileInput = c} onChange={this.onChange.bind(this)}/>
								</div>
								<div className="col-xs-12">
									<p className="sm-error sm-import-error">{this.state.error}</p>
								</div>
								<div className="sm-upload-button">
									<button className="sm-button" onClick={this.onClickImport}>Import</button>
								</div>
							</div>
							<div className="sm-sheet sm-sheet-mid">
								<p className="sm-import-text">
									Import your file and create your optimised builds for your team !
									<br/>
									<br/>
									Take a look of all your monsters and runes like in game !
									<br/>
									<br/>
									<a className="sm-button" href="https://github.com/kakaroto/SWProxy" target="_blank">How to get your Json File ?</a>
								</p>
							</div>
						</div>
					</div>
					<div className="col-xs-12 col-sm-6">
						<div className="sm-import-img-content">
							<img src="assets/images/upload.png" alt="Summoners War Homunculus" className="sm-import-img" />
						</div>
					</div>
				</div>
			</div>
		);
	}

}
export default Import;
