import AppHelper from 'helpers/AppHelper';
import AuthHelper from 'helpers/AuthHelper';
import DefaultHelper from 'helpers/DefaultHelper';

/* This class was auto-generated by the JavaScriptWriter */
class ImportData {

	register(obj) {
		this.obj = obj
		this.init()
	}

	unregister() {
	}

	init() {
		this.obj.setState({onClickImport: this.onClickImport.bind(this)})
	}

	onClickImport() {
		var f = this.obj.fileInput.files[0]; 

	    if (f) {
	      var r = new FileReader();
	      r.onload = function(e) { 
		    var contents = e.target.result;
		    DefaultHelper.postUserImport({data: contents, userId: AuthHelper.getEntityId()})
	      }
	      r.readAsText(f);
	    } else { 
	      console.log("Failed to load file");
	    }
	}


}
var ImportObj = new ImportData();
export default ImportObj;
