import React from 'react';
import SWPanel from 'components-lib/ui/SWPanel'
import BuildProfilData from 'components-lib/buildProfil/BuildProfilData';
import MonsterConfigList from 'components-lib/monsterConfigList/MonsterConfigList';
import BuildResults from 'components-lib/buildResults/BuildResults';

import './BuildProfil.scss';

/* This class was auto-generated by the JavaScriptWriter */
class BuildProfil extends React.Component {

    constructor(props) {
        super(props);
    }

    componentWillMount() {
        BuildProfilData.register(this)
    }

    componentWillUnmount() {
        BuildProfilData.unregister()
    }

    _buildBuildProfil(id) {
        if(id === "config" )
            return (<MonsterConfigList />)
        else
            return (<BuildResults buildResults={this.state.buildResults}/>)
    }

    render() { 
        return (
            <SWPanel className="sm-build-profil" size="lg">
                <i className="glyphicon glyphicon-expand sm-build-profil-expand" onClick={this.onClickExpand}></i>
                <div className="sm-build-expand-infos">
                    Expand screen<br/>
                </div>
                <div className={"sm-build-tab sm-build-tab-info " + (this.state.currentPage === 'config' ? 'sm-build-tab-active' : "")} 
                    onClick={this.onClickConfig}>
                    Config
                </div>
                <div className={"sm-build-tab sm-build-tab-rune " + (this.state.currentPage === 'results' ? 'sm-build-tab-active' : "") + (!this.state.buildHaveResults ? "sm-build-tab-hide" : "")} 
                    onClick={this.onClickResults}>
                    Results
                </div>
                { this._buildBuildProfil(this.state.currentPage) }
            </SWPanel>
    )}

}
export default BuildProfil;
