import React from 'react';
import RegisterData from 'components/lib/register/RegisterData';
import './Register.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Register extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		RegisterData.register(this)
	}

	componentWillUnmount() {
		RegisterData.unregister()
	}

	render() {
		return (
			<div className="sm-register">
				<div className="col-xs-12">
					<h3 className="sm-register-title">Register</h3>
				</div>
				<div className="col-xs-12">
					<div className="sm-content">
						<label className="sm-label">Name</label>
						<input type="text" className="sm-input" value={this.state.name} onChange={this.state.onChange.bind(this, 'name')}/>
						<label className="sm-label sm-register-label-mid">Mail</label>
						<input type="text" className="sm-input" value={this.state.mail} onChange={this.state.onChange.bind(this, 'mail')}/>
						<label className="sm-label sm-register-label-mid">Password</label>
						<input type="text" className="sm-input" value={this.state.password} onChange={this.state.onChange.bind(this, 'password')}/>
						<a onClick={this.state.onClick} className="sm-register-login">Go to Login</a>
					</div>
				</div>
				<div className="col-xs-12">
					<div className="sm-register-button">
						<button className="sm-button" onClick={this.state.onSubmit}>Register</button>
					</div>
				</div>
			</div>
		);
	}

}
export default Register;
