
/* This class was auto-generated by the JavaScriptWriter */
class ElemType {

	static get WATER() {
		return _WATER
	}

	static get FIRE() {
		return _FIRE
	}

	static get WIND() {
		return _WIND
	}

	static get LIGHT() {
		return _LIGHT
	}

	static get DARK() {
		return _DARK
	}

	static get VALUES() {
		return [
			_WATER,
			_FIRE,
			_WIND,
			_LIGHT,
			_DARK,
		]
	}

	static get(id) {
		return id && ElemType[id.toUpperCase()]
	}

}
let _WATER = { key: 'Water' }
let _FIRE = { key: 'Fire' }
let _WIND = { key: 'Wind' }
let _LIGHT = { key: 'Light' }
let _DARK = { key: 'Dark' }
export default ElemType
