
/* This class was auto-generated by the JavaScriptWriter */
class PosType {

	static get 1() {
		return _1
	}

	static get 2() {
		return _2
	}

	static get 3() {
		return _3
	}

	static get 4() {
		return _4
	}

	static get 5() {
		return _5
	}

	static get 6() {
		return _6
	}

	static get VALUES() {
		return [
			_1,
			_2,
			_3,
			_4,
			_5,
			_6,
		]
	}

	static get(id) {
		return id && PosType[id.toUpperCase()]
	}

}
let _1 = { key: '1' }
let _2 = { key: '2' }
let _3 = { key: '3' }
let _4 = { key: '4' }
let _5 = { key: '5' }
let _6 = { key: '6' }
export default PosType
