
/* This class was auto-generated by the JavaScriptWriter */
class RoleType {

	static get ATTACK() {
		return _ATTACK
	}

	static get DEFENSE() {
		return _DEFENSE
	}

	static get SUPPORT() {
		return _SUPPORT
	}

	static get MATERIAL() {
		return _MATERIAL
	}

	static get HP() {
		return _HP
	}

	static get VALUES() {
		return [
			_ATTACK,
			_DEFENSE,
			_SUPPORT,
			_MATERIAL,
			_HP,
		]
	}

	static get(id) {
		return id && RoleType[id.toUpperCase()]
	}

}
let _ATTACK = { key: 'Attack' }
let _DEFENSE = { key: 'Defense' }
let _SUPPORT = { key: 'Support' }
let _MATERIAL = { key: 'Material' }
let _HP = { key: 'Hp' }
export default RoleType
