
/* This class was auto-generated by the JavaScriptWriter */
class SetType {

	static get ENERGY() {
		return _ENERGY
	}

	static get SWIFT() {
		return _SWIFT
	}

	static get FATAL() {
		return _FATAL
	}

	static get RAGE() {
		return _RAGE
	}

	static get VAMPIRE() {
		return _VAMPIRE
	}

	static get FOCUS() {
		return _FOCUS
	}

	static get GUARD() {
		return _GUARD
	}

	static get SHIELD() {
		return _SHIELD
	}

	static get REVENGE() {
		return _REVENGE
	}

	static get WILL() {
		return _WILL
	}

	static get NEMESIS() {
		return _NEMESIS
	}

	static get DESTROY() {
		return _DESTROY
	}

	static get DESPAIR() {
		return _DESPAIR
	}

	static get VIOLENT() {
		return _VIOLENT
	}

	static get FIGHT() {
		return _FIGHT
	}

	static get DETERMINATION() {
		return _DETERMINATION
	}

	static get ENHANCE() {
		return _ENHANCE
	}

	static get ACCURACY() {
		return _ACCURACY
	}

	static get TOLERANCE() {
		return _TOLERANCE
	}

	static get BLADE() {
		return _BLADE
	}

	static get VALUES() {
		return [
			_ENERGY,
			_SWIFT,
			_FATAL,
			_RAGE,
			_VAMPIRE,
			_FOCUS,
			_GUARD,
			_SHIELD,
			_REVENGE,
			_WILL,
			_NEMESIS,
			_DESTROY,
			_DESPAIR,
			_VIOLENT,
			_FIGHT,
			_DETERMINATION,
			_ENHANCE,
			_ACCURACY,
			_TOLERANCE,
			_BLADE,
		]
	}

	static get(id) {
		return id && SetType[id.toUpperCase()]
	}

}
let _ENERGY = { key: 'Energy' }
let _SWIFT = { key: 'Swift' }
let _FATAL = { key: 'Fatal' }
let _RAGE = { key: 'Rage' }
let _VAMPIRE = { key: 'Vampire' }
let _FOCUS = { key: 'Focus' }
let _GUARD = { key: 'Guard' }
let _SHIELD = { key: 'Shield' }
let _REVENGE = { key: 'Revenge' }
let _WILL = { key: 'Will' }
let _NEMESIS = { key: 'Nemesis' }
let _DESTROY = { key: 'Destroy' }
let _DESPAIR = { key: 'Despair' }
let _VIOLENT = { key: 'Violent' }
let _FIGHT = { key: 'Fight' }
let _DETERMINATION = { key: 'Determination' }
let _ENHANCE = { key: 'Enhance' }
let _ACCURACY = { key: 'Accuracy' }
let _TOLERANCE = { key: 'Tolerance' }
let _BLADE = { key: 'Blade' }
export default SetType
