
/* This class was auto-generated by the JavaScriptWriter */
class StatType {

	static get ATK() {
		return _ATK
	}

	static get ATKFLAT() {
		return _ATKFLAT
	}

	static get DEF() {
		return _DEF
	}

	static get DEFFLAT() {
		return _DEFFLAT
	}

	static get SPD() {
		return _SPD
	}

	static get CRATE() {
		return _CRATE
	}

	static get CDMG() {
		return _CDMG
	}

	static get RES() {
		return _RES
	}

	static get ACC() {
		return _ACC
	}

	static get HP() {
		return _HP
	}

	static get HPFLAT() {
		return _HPFLAT
	}

	static get VALUES() {
		return [
			_ATK,
			_ATKFLAT,
			_DEF,
			_DEFFLAT,
			_SPD,
			_CRATE,
			_CDMG,
			_RES,
			_ACC,
			_HP,
			_HPFLAT,
		]
	}

	static get(id) {
		return id && StatType[id.toUpperCase()]
	}

}
let _ATK = { key: 'Atk' }
let _ATKFLAT = { key: 'AtkFlat' }
let _DEF = { key: 'Def' }
let _DEFFLAT = { key: 'DefFlat' }
let _SPD = { key: 'Spd' }
let _CRATE = { key: 'Crate' }
let _CDMG = { key: 'Cdmg' }
let _RES = { key: 'Res' }
let _ACC = { key: 'Acc' }
let _HP = { key: 'Hp' }
let _HPFLAT = { key: 'HpFlat' }
export default StatType
