import React from 'react';
import MonsterProfilData from 'components-lib/monsterProfil/MonsterProfilData';
import MonsterInfos from 'components-lib/monsterInfos/MonsterInfos';
import MonsterRunes from 'components-lib/monsterRunes/MonsterRunes';
import './MonsterProfil.scss';

/* This class was auto-generated by the JavaScriptWriter */
class MonsterProfil extends React.Component {

    constructor(props) {
        super(props);
    }

    componentWillMount() {
        MonsterProfilData.register(this)
    }

    componentWillUnmount() {
        MonsterProfilData.unregister()
    }

    _buildMonsterProfil(id) {
        if(id === "infos" )
            return (<MonsterInfos monster={this.state.monster}/>)
        else
            return (<MonsterRunes runes={this.state.runes}/>)
    }

    render() { 
        return (
        <div className="sm-monsterprofil">
           <div className="sm-sheet">
                <div className={"sm-monster-tab " + (this.state.currentPage === 'infos' ? 'sm-monster-tab-active' : "")} onClick={this.onClickInfos}>Infos</div>
                <div className={"sm-monster-tab sm-monster-mid " + (this.state.currentPage === 'runes' ? 'sm-monster-tab-active' : "") + (!this.state.monsterHaveRunes ? "sm-monster-tab-hide" : "")} onClick={this.onClickRunes}>Runes</div>
                { this._buildMonsterProfil(this.state.currentPage) }
            </div> 
        </div>
    )}

}
export default MonsterProfil;
