import React from 'react';
import HomeData from 'components/home/HomeData';
import Login from 'components/lib/login/Login';
import Register from 'components/lib/register/Register';
import './Home.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Home extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		HomeData.register(this)
	}

	componentWillUnmount() {
		HomeData.unregister()
	}

	buildData() {
		if(this.state.isLoginCompo)
			return (<Login onClick={this.state.onClick.bind(this)}/>)
		else
			return (<Register onClick={this.state.onClick.bind(this)}/>)
	}

	render() {
		return (
			<div className='ap-home'>
				<div className="row">
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet">
							<div className="row">
								{this.buildData()}
							</div>
						</div>
					</div>
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet">
							<p className="sm-home-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
						</div>
						<img className="sm-home-img" src={"assets/images/summonerswar.png"} />
					</div>
				</div>
			</div>
		);
	}

}
export default Home;
