import React from 'react';
import HomeData from 'components/home/HomeData';
import './Home.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Home extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		HomeData.register(this)
	}

	componentWillUnmount() {
		HomeData.unregister()
	}

	render() {
		return (
			<div className='ap-home'>
				<div className="row">
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet">
							<div className="row">
								<form className="sm-login">
									<div className="col-xs-12">
										<h3 className="sm-login-title">Login</h3>
									</div>
									<div className="col-xs-12">
										<div className="sm-content">
											<label className="sm-label">Mail</label>
											<input type="text" className="sm-input" />
											<label className="sm-label sm-login-label-mid">Password</label>
											<input type="text" className="sm-input"/>
											<a href="register" className="sm-login-register">Create an Account</a>
										</div>
									</div>
									<div className="col-xs-12">
										<div className="sm-login-button">
											<input className="sm-button" type="submit" value="Login"/>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet">
							<p className="sm-home-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
						</div>
						<img className="sm-home-img" src={"assets/images/summonerswar.png"} />
					</div>
				</div>
			</div>
		);
	}

}
export default Home;
