import AppHelper from 'helpers/AppHelper'
import AuthHelper from 'helpers/AuthHelper'

import {Utils, BaseData}  from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class BuildResultsData extends BaseData {
	register(obj) {
		super.register(obj)

        this.obj.onClickShow = this.onClickShow.bind(this)

        let buildResults = this.obj.props.buildResults

        let showResult = {}
        for (let key in buildResults)
        	showResult[key] = false

		this.obj.state = {  
			showResult: showResult
		}
	}

    onClickShow(id) {
    	let showResult = this.getState('showResult')
    	showResult[id] = !showResult[id]
    	this.setState({showResult: showResult})
    }
    
    unregister() {
    }
}

var BuildResultsDataObj = new BuildResultsData();
export default BuildResultsDataObj;