import React from 'react';

import BuildResult from 'components-lib/buildResult/BuildResult'

import BuildResultsData from 'components-lib/buildResults/BuildResultsData';
import {Utils}  from 'ap-react-bootstrap'

import './BuildResults.scss';

/* This class was auto-generated by the JavaScriptWriter */
class BuildResults extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		BuildResultsData.register(this)
	}

	componentWillUnmount() {
		BuildResultsData.unregister()
	}

	componentWillReceiveProps(newProps) {
		BuildResultsData.update(newProps)
	}

	_buildBuildResult(buildResult) {
		return (<BuildResult key={buildResult.id} buildResult={buildResult}/>)
	}

	render() {
		return (
			<div className="sm-build-results">
			 	<div className="sm-content">
			 		{Utils.map(this.state.buildResults, this._buildBuildResult.bind(this))}
			 	</div>
		 	</div>
		)
	}
}
export default BuildResults;