import AppHelper from 'helpers/AppHelper'
import AuthHelper from 'helpers/AuthHelper'
import MonsterHelper from 'helpers/MonsterHelper'
import MonsterConfigHelper from 'helpers/MonsterConfigHelper'

import StatType from 'utils/constants/StatType'
import SetType from 'utils/constants/SetType'
import {Utils, BaseData}  from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class MonsterConfigData extends BaseData {

	register(obj) {
		super.register(obj)

		let monsterConfig = this.obj.props.monsterConfig

		let monsters = {}
		for(let key in MonsterHelper.getData())
			monsters[key] = MonsterHelper.getData()[key].name.split(" ")[0]

		let monster = ""
		let monsterImage = "default-monster"
		if(monsterConfig.monsterId && monsters[monsterConfig.monsterId]) {
			monster = monsters[monsterConfig.monsterId]
			monsterImage = monsters[monsterConfig.monsterId]
		}

		let statTypeValues = []
        for(let i = 0; i < StatType.VALUES.length; i++)
        	if (StatType.VALUES[i].key != 'AtkFlat' && StatType.VALUES[i].key != 'DefFlat' && StatType.VALUES[i].key != 'HpFlat')
            	statTypeValues.push(StatType.VALUES[i].key)

        let setTypeValues = []
        for(let i = 0; i < SetType.VALUES.length; i++)
            setTypeValues.push(SetType.VALUES[i].key)
        
       	let requiredStats = {}
        for(let key in StatType.VALUES)
        	if(monsterConfig['required'+ StatType.VALUES[key].key])
	        	requiredStats[StatType.VALUES[key].key] = monsterConfig['required'+ StatType.VALUES[key].key]

	    let notationStats = {}
        for(let key in StatType.VALUES)
        	if(monsterConfig['notation'+ StatType.VALUES[key].key])
	        	notationStats[StatType.VALUES[key].key] = monsterConfig['notation'+ StatType.VALUES[key].key]

        let sets = []
        for(let i = 1; i < 4; i++)
        	if(monsterConfig['set'+i]) 
        		sets.push(monsterConfig['set'+i])

        let statsTypeRune2 = []
        for(let i = 0; i < StatType.VALUES.length; i++)
        	if (StatType.VALUES[i].key != 'Res' && StatType.VALUES[i].key != 'Acc' && StatType.VALUES[i].key != 'Crate' && StatType.VALUES[i].key != 'Cdmg')
            	statsTypeRune2.push(StatType.VALUES[i].key)

        let statsTypeRune4 = []
        for(let i = 0; i < StatType.VALUES.length; i++)
        	if (StatType.VALUES[i].key != 'Res' && StatType.VALUES[i].key != 'Acc' && StatType.VALUES[i].key != 'Spd')
            	statsTypeRune4.push(StatType.VALUES[i].key)

        let statsTypeRune6 = []
        for(let i = 0; i < StatType.VALUES.length; i++)
        	if (StatType.VALUES[i].key != 'Crate' && StatType.VALUES[i].key != 'Cdmg' && StatType.VALUES[i].key != 'Spd')
            	statsTypeRune6.push(StatType.VALUES[i].key)

        let isExpanded = AppHelper.getData("/isExpanded")

        this.obj.onClickShow = this.onClickShow.bind(this)
        this.obj.onClickSubmit = this.onClickSubmit.bind(this)
        this.obj.onChangeInput = this.onChangeInput.bind(this)
        this.obj.onChangeSelect = this.onChangeSelect.bind(this)
        this.obj.onClickDeleteStat = this.onClickDeleteStat.bind(this)
        this.obj.onChangeMonsterName = this.onChangeMonsterName.bind(this)
        this.obj.onChangeBrokenSet = this.onChangeBrokenSet.bind(this)
        this.obj.onInputNotation = this.onInputNotation.bind(this)
        this.obj.onClickMonster = this.onClickMonster.bind(this)
        this.obj.onChangeOrderAtk = this.onChangeOrderAtk.bind(this)
        this.obj.onChangeRuneStats = this.onChangeRuneStats.bind(this)

		this.obj.state = {
            statTypeValues: statTypeValues,
            setTypeValues: setTypeValues,

            requiredStatsIsOpen: false,
            notationStatsIsOpen: false,
            setsIsOpen: false,
            runeStatsIsOpen: false,
            
            monsterConfig: monsterConfig,

            monsters: monsters,
            monsterName: monster,
            monsterImage: monsterImage,

            requiredStatsSelect: statTypeValues[0],
            requiredStatsInput: "0",
            requiredStats: requiredStats,

            notationStatsSelect: statTypeValues[0],
            notationStatsInput: "0",
            notationStats: notationStats,

            setsSelect: setTypeValues[0],
            sets: sets,

            statsTypeRune2: statsTypeRune2,
            statsTypeRune4: statsTypeRune4,
            statsTypeRune6: statsTypeRune6,

            isExpanded: isExpanded,

            monstersList: {},
            monstersListShow: false
        }

        AppHelper.register('/isExpanded', this, this.isExpanded.bind(this))
	}

	update(props) {
		let monsterConfig = props.monsterConfig
		let monster = ""
		let monsterImage = "default-monster"
		if(monsterConfig.monsterId && this.obj.state.monsters[monsterConfig.monsterId]) {
			monster = this.obj.state.monsters[monsterConfig.monsterId]
			monsterImage = this.obj.state.monsters[monsterConfig.monsterId]
		}

		let requiredStats = {}
        for(let key in StatType.VALUES)
        	if(monsterConfig['required'+ StatType.VALUES[key].key])
	        	requiredStats[StatType.VALUES[key].key] = monsterConfig['required'+ StatType.VALUES[key].key]

	    let notationStats = {}
        for(let key in StatType.VALUES)
        	if(monsterConfig['notation'+ StatType.VALUES[key].key])
	        	notationStats[StatType.VALUES[key].key] = monsterConfig['notation'+ StatType.VALUES[key].key]

        let sets = []
        for(let i = 1; i < 4; i++)
        	if(monsterConfig['set'+i]) 
        		sets.push(monsterConfig['set'+i])


		this.setState({        
            monsterConfig: monsterConfig,
            monsterName: monster,
            monsterImage: monsterImage,

            requiredStats: requiredStats,
            notationStats: notationStats,
            sets: sets
        })
	}

	onClickMonster(monster) {
		let monsters = MonsterHelper.getData()

		for(let key in monsters) {
			if(monsters[key].name.toUpperCase() == monster.name.toUpperCase()) {
				let monsterConfig = this.getState('monsterConfig')
				monsterConfig.monsterId = monsters[key].id
				AppHelper.put("monstersConfig/" + monsterConfig.id, monsterConfig)

				this.setState({
					monsterConfig: monsterConfig,
					monsterName: monster.name, 
					monsterImage: monster.name,
					monstersListShow: false
				})
				break
			}
		}
	}

	onChangeRuneStats(id, event) {
		let build = AppHelper.getData('currentBuild')
		AppHelper.put('/canSave/' + build.id, true)
		
		let monsterConfig = this.getState('monsterConfig')
		monsterConfig[id] = event.target.value
		this.setState({monsterConfig: monsterConfig})
	}

	onChangeOrderAtk(event) {
		let build = AppHelper.getData('currentBuild')
		AppHelper.put('/canSave/' + build.id, true)
		
		let monsterConfig = this.getState('monsterConfig')
		monsterConfig.orderAtk = event.target.value
		this.setState({monsterConfig: monsterConfig})
	}

	isExpanded() {
		let isExpanded = AppHelper.getData("/isExpanded")
		this.setState({isExpanded: isExpanded})
	}

	onInputNotation(event) {
		this.setState({notationStatsInput: event.target.value})
	}

	onChangeMonsterName(event) {
		let build = AppHelper.getData('/currentBuild')
		AppHelper.put('/canSave/' + build.id, true)

		let monsters = Utils.map(MonsterHelper.getData())
		monsters = monsters.filter(function(monster) {
			if (monster.name.toUpperCase().indexOf(event.target.value.toUpperCase()) >= 0)
	            return true
	        return false
		})

		this.setState({
			monsterName: event.target.value, 
			monstersList: monsters,
			monstersListShow: true
		})
	}

	onChangeBrokenSet(event) {
		let build = AppHelper.getData('currentBuild')
		AppHelper.put('/canSave/' + build.id, true)
		
		let monsterConfig = this.getState('monsterConfig')
		monsterConfig.brokenSet = !monsterConfig.brokenSet
		this.setState({monsterConfig: monsterConfig})
	}

	onClickDeleteStat(id, stat) {
		let build = AppHelper.getData('currentBuild')
		AppHelper.put('/canSave/' + build.id, true)
		
		if( id== 'sets')
			this.getState('sets').splice(stat, 1)
		else
			delete(this.getState(id)[stat])

		this._fillMonsterConfig(id)
	}

	onChangeInput(id, event) {
		this.obj.state[id + "Input"] = event.target.value
	}

	onChangeSelect(id, event) {
		this.obj.state[id + "Select"] = event.target.value
	}

	onClickShow(id) {
		this.obj.state[id + "IsOpen"] = !this.getState(id + 'IsOpen')
		this.setState()
	}

	_fillMonsterConfig(id) {
		let monsterConfig = this.getState('monsterConfig')

		if(id == 'requiredStats') {
        	for(let key in StatType.VALUES)
        		if(this.getState('requiredStats')[StatType.VALUES[key].key])
        			monsterConfig['required'+ StatType.VALUES[key].key] = parseInt(this.getState('requiredStats')[StatType.VALUES[key].key])
        		else
        			delete(monsterConfig['required'+ StatType.VALUES[key].key])
		} else if(id == 'notationStats') {
			for(let key in StatType.VALUES) 
				if(this.getState('notationStats')[StatType.VALUES[key].key])
        			monsterConfig['notation'+ StatType.VALUES[key].key] = parseInt(this.getState('notationStats')[StatType.VALUES[key].key])
        		else
        			delete(monsterConfig['notation'+ StatType.VALUES[key].key])
		} else {
			let count = 1
			for(let key in this.getState('sets')) {
				monsterConfig['set' + count] = this.getState('sets')[key]
				count++
			}
			for (let i = count; i < 4; i++)
				delete(monsterConfig['set' + i])
		}

		this.setState({monsterConfig: monsterConfig})
	}

	onClickSubmit(id) {
		let build = AppHelper.getData('currentBuild')
		AppHelper.put('/canSave/' + build.id, true)
		
		if(id == 'sets')
			this.getState(id).push(this.getState(id + 'Select'))
		else
			this.getState(id)[this.getState(id + 'Select')] = this.getState(id + 'Input')

		this._fillMonsterConfig(id)
	}

	unregister() {
	}

}

export default MonsterConfigData;
