import React from 'react';
import MonstersData from 'components/monsters/MonstersData';
import {Rater, Utils}  from 'ap-react-bootstrap';
import Monster from 'components/lib/monster/Monster';
import MonsterInfos from 'components/lib/monsterInfos/MonsterInfos';
import MonsterRunes from 'components/lib/monsterRunes/MonsterRunes';
import './Monsters.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Monsters extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		MonstersData.register(this)
	}

	componentWillUnmount() {
		MonstersData.unregister()
	}

	buildMonster(monster) {
		return (<Monster key={monster.id} monster={monster} onClick={this.state.onClickMonster}/>)
	}

	buildMonsterInfos(id) {
		if(id == "infos" )
			return (<MonsterInfos monster={this.state.monster}/>)
		else
			return (<MonsterRunes monster={this.state.monster}/>)
	}

	render() {
		return (
			<div className='ap-monsters'>
				<div className="row">
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet sm-monster-filters-element">
							<img className="sm-monster-filter-element" src="assets/images/elements/water.png"/>
							<img className="sm-monster-filter-element" src="assets/images/elements/fire.png"/>
							<img className="sm-monster-filter-element" src="assets/images/elements/wind.png"/>
							<img className="sm-monster-filter-element" src="assets/images/elements/light.png"/>
							<img className="sm-monster-filter-element" src="assets/images/elements/dark.png"/>
						</div>
						<div className="sm-monster-list">
							{Utils.map(this.state.monsters, this.buildMonster.bind(this))}
						</div>
					</div>
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet">
							<div className={"sm-monster-tab " + (this.state.currentPage == 'infos' ? 'sm-monster-tab-active' : "")} onClick={this.state.onClickInfos}>Infos</div>
							<div className={"sm-monster-tab sm-monster-mid "+ (this.state.currentPage == 'runes' ? 'sm-monster-tab-active' : "")} onClick={this.state.onClickRune}>Runes</div>
							{ this.buildMonsterInfos(this.state.currentPage) }
						</div>
					</div>
					<div className="col-xs-12">
						<div className="sm-sheet sm-monster-filters-top">
							<ul className="sm-monster-filters">
								<li>
									<label className="sm-label">Grade</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Lvl</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Attribute</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Recent</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		);
	}

}
export default Monsters;
