import React from 'react';
import MonstersData from 'components/monsters/MonstersData';
import './Monsters.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Monsters extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		MonstersData.register(this)
	}

	componentWillUnmount() {
		MonstersData.unregister()
	}

	render() {
		return (
			<div className='ap-monsters'>
				<div className="row">
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet sm-monster-filters-element">
							<img className="sm-monster-filter-element" src="assets/images/water.png"/>
							<img className="sm-monster-filter-element" src="assets/images/fire.png"/>
							<img className="sm-monster-filter-element" src="assets/images/wind.png"/>
							<img className="sm-monster-filter-element" src="assets/images/light.png"/>
							<img className="sm-monster-filter-element" src="assets/images/dark.png"/>
						</div>
						<div className="sm-monster-list">
							<div className="sm-monster">
								<img className="sm-monster-image sm-monster-active" src="assets/images/monster.jpg"/>
								<i className="glyphicon glyphicon-star sm-monster-star"></i>
								<i className="glyphicon glyphicon-star sm-monster-star"></i>
								<i className="glyphicon glyphicon-star sm-monster-star"></i>
								<i className="glyphicon glyphicon-star sm-monster-star"></i>
								<i className="glyphicon glyphicon-star sm-monster-star"></i>
								<i className="glyphicon glyphicon-star sm-monster-star"></i>
								<span className="sm-monster-lvl">50</span>
							</div>
							<div className="sm-monster">
								<img className="sm-monster-image" src="assets/images/default-monster.png"/>
							</div>
						</div>
					</div>
					<div className="col-xs-12 col-md-6">
						<div className="sm-sheet">
							<div className="sm-monster-tab sm-monster-tab-active">Infos</div>
							<div className="sm-monster-tab sm-monster-mid">Runes</div>
							<div className="sm-monster-infos">
								<div className="sm-content sm-monster-content">
									<div className="sm-monster-info">
										<div className="row">
											<div className="col-xs-12 col-sm-8">
												<img className="sm-monster-element" src="assets/images/water.png"/>
												<span className="sm-monster-name">Chevalier magique</span>
											</div>
											<div className="col-xs-12 col-sm-4">
												<i className="glyphicon glyphicon-star sm-monster-star"></i>
												<i className="glyphicon glyphicon-star sm-monster-star"></i>
												<i className="glyphicon glyphicon-star sm-monster-star"></i>
												<i className="glyphicon glyphicon-star sm-monster-star"></i>
												<i className="glyphicon glyphicon-star sm-monster-star"></i>
												<i className="glyphicon glyphicon-star sm-monster-star"></i>
											</div>
										</div>
									</div>
									<div className="sm-monster-info">
										<div className="row">
											<div className="col-xs-2">
												<div className="sm-monster-xp">XP</div>
											</div>
											<div className="col-xs-10">
												<div className="progress sm-monster-progressbar">
												  	<div className="progress-bar sm-monster-progressbar-value" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">
													    60%
												  	</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div className="sm-monster-stats">
									<div className="col-xs-5">
										<ul className="sm-monster-keys">
											<li>Level</li>
											<li>HP</li>
											<li>ATK</li>
											<li>DEF</li>
											<li>SPD</li>
											<li className="sm-monster-separator"></li>
											<li>CRIT Rate</li>
											<li>CRIT Dmg</li>
											<li>RES</li>
											<li>ACC</li>
										</ul>
									</div>
									<div className="col-xs-7">
										<ul className="sm-monster-values">
											<li>27 / 35</li>
											<li>5445 <span className="sm-monster-extra">+3128</span></li>
											<li>399 <span className="sm-monster-extra">+312</span></li>
											<li>413 <span className="sm-monster-extra">+38</span></li>
											<li>102 <span className="sm-monster-extra">+2</span></li>
											<li className="sm-monster-separator"></li>
											<li>18%</li>
											<li>50%</li>
											<li>23%</li>
											<li>0%</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div className="col-xs-12">
						<div className="sm-sheet sm-monster-filters-top">
							<ul className="sm-monster-filters">
								<li>
									<label className="sm-label">Grade</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Lvl</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Attribute</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Recent</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		);
	}

}
export default Monsters;
