import AppHelper from 'helpers/AppHelper';

/* This class was auto-generated by the JavaScriptWriter */
class MonstersData {

	register(obj) {
		this.obj = obj
	}

	unregister() {
	}

}
var MonstersObj = new MonstersData();
export default MonstersObj;
