import React from 'react';
import BuildsListData from 'components-lib/buildsList/BuildsListData';

import {Utils, FormSelect}  from 'ap-react-bootstrap'

import './BuildsList.scss';

/* This class was auto-generated by the JavaScriptWriter */
class BuildsList extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		BuildsListData.register(this)
	}

	componentWillUnmount() {
		BuildsListData.unregister()
	}

	_buildBuild(build) {
		return (
			<li key={build.id} onClick={this.onClickBuild.bind(this, build)}>
				<div className={"sm-build " + (this.state.build.id == build.id? "sm-build-active" : "")}><span>{build.name}</span></div>
			</li>
		)
	}

	render() {
		return (
			<div className="sm-sheet sm-builds-list">
			 	<ul>
			 		{ Utils.map(this.state.builds, this._buildBuild.bind(this))}
			 		<li>
						<div className="sm-build">
							<i className="glyphicon glyphicon-plus-sign sm-build-add" onClick={this.onClickAddBuild.bind(this)}></i>
						</div>
					</li>
			 	</ul>
		 	</div>
		)
	}
}
export default BuildsList;