import React from 'react';
import BuildsListData from 'components-lib/buildsList/BuildsListData';
import SWPanel from 'components-lib/ui/SWPanel'

import {Utils, FormSelect}  from 'ap-react-bootstrap'

import './BuildsList.scss';

/* This class was auto-generated by the JavaScriptWriter */
class BuildsList extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		BuildsListData.register(this)
	}

	componentWillUnmount() {
		BuildsListData.unregister()
	}

	_buildBuild(build) {
		return (
			<li key={build.id} onClick={this.onClickBuild.bind(this, build)} className="sm-builds-list-li">
				<div className={"sm-build " + (this.state.build.id == build.id? "sm-build-active" : "")}><span>{build.name}</span></div>
			</li>
		)
	}

	render() {
		return (
			<SWPanel className="sm-builds-list">
			 	<ul>
			 		{ Utils.map(this.state.builds, this._buildBuild.bind(this))}
			 		<li className="sm-builds-add">
			 			<i className="glyphicon glyphicon-plus-sign" onClick={this.onClickAddBuild.bind(this)}></i>
					</li>
			 	</ul>
		 	</SWPanel>
		)
	}
}
export default BuildsList;