import React from 'react';
import BuildsListData from 'components-lib/buildsList/BuildsListData';
import SWPanel from 'components-lib/ui/SWPanel'

import {Utils, FormSelect}  from 'ap-react-bootstrap'

import './BuildsList.scss';

/* This class was auto-generated by the JavaScriptWriter */
class BuildsList extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		BuildsListData.register(this)
	}

	componentWillUnmount() {
		BuildsListData.unregister()
	}

	_buildBuild(build) {
		return (
			<li key={build.id} onClick={this.onClickBuild.bind(this, build)} className="sm-builds-list-li">
				<div className={"sm-button sm-build " + (this.state.build.id == build.id? "sm-build-active" : "")}>{build.name}</div>
				<i className="glyphicon glyphicon-remove" onClick={this.onClickDelete.bind(this, build.id)}></i>
			</li>
		)
	}

	render() {
		return (
			<SWPanel className="sm-builds-list">
				<i className="glyphicon glyphicon-refresh sm-build-refresh" onClick={this.onClickRefresh.bind(this)}></i>
				<div className="sm-build-refresh-infos">
					Refresh your builds and check their status<br/>
				</div>
			 	<ul>
			 		{ Utils.map(this.state.builds, this._buildBuild.bind(this))}
			 		<li className="sm-builds-add" onClick={this.onClickAddBuild.bind(this)}>
			 			<i className="glyphicon glyphicon-plus-sign"></i>
			 			<span >Add New Build</span>
					</li>
			 	</ul>
		 	</SWPanel>
		)
	}
}
export default BuildsList;