import AppHelper from 'helpers/AppHelper'
import BuildHelper from 'helpers/BuildHelper'

import {Utils, BaseData}  from 'ap-react-bootstrap'

/* This class was auto-generated by the JavaScriptWriter */
class BuildsListData extends BaseData {
	register(obj) {
		super.register(obj)

		this.obj.onClickAddBuild = this.onClickAddBuild.bind(this)
		this.obj.onClickBuild = this.onClickBuild.bind(this)

		this.obj.state = {  
			builds: [],
			build: {}
		}

        this._buildBuildsData()

	}

	onClickBuild(build) {
        AppHelper.put('/build/' + this.build.id, false)
        this.build = build
        AppHelper.put('/build/' + build.id, true)
        AppHelper.put('/currentBuild', build)
        this.setState({	build: build })
    }

    _buildBuildsData() {
        let builds = Utils.map(BuildHelper.getData())
        this.build = builds.length ? builds[0] : null
        if (this.build) {
            AppHelper.put('/build/' + this.build.id, true)
            AppHelper.put('/currentBuild', this.build)
        }
        this.setState({ builds: builds, build: this.build })
    }

	unregister() {}

	onClickAddBuild() {
		console.log("ADD")
	}

}

var BuildsListDataObj = new BuildsListData();
export default BuildsListDataObj;