package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class APAuthPasswordBean {

	public String username;
	public String password;
	public String oldPassword;

}
