package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class BuildResultBean {

	public String buildId;
	public String userId;
	public Double eval;
	public String id;

}
