package org.ap.summonerwar.bean;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class BuildResultBean {

	public String buildId;
	public String userId;
	public String id;
	public List<Integer> creationDate;

}
