package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class MonsterConfigBean {

	public String monsterId;
	public String buildId;
	public Integer requiredDef;
	public Integer notationSpd;
	public Integer requiredAcc;
	public Integer notationHp;
	public Integer requiredHpFlat;
	public Integer requiredDefFlat;
	public Integer requiredAtkFlat;
	public Integer requiredCrate;
	public Integer notationHpFlat;
	public String id;
	public Integer requiredAtk;
	public Integer requiredCdmg;
	public Integer notationCdmg;
	public Integer notationAcc;
	public Integer notationDef;
	public String set3;
	public Integer requiredRes;
	public String set2;
	public Integer requiredSpd;
	public Integer notationDefFlat;
	public Integer requiredHp;
	public Integer notationAtkFlat;
	public Integer notationCrate;
	public Integer notationAtk;
	public String set1;
	public Integer notationRes;

}
