package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class MonsterResultBean {

	public String rune6;
	public String teamResultId;
	public String rune3;
	public String rune2;
	public String rune5;
	public String rune4;
	public String rune1;
	public String userId;
	public String monsterConfigId;
	public Integer acc;
	public Integer res;
	public Integer def;
	public Integer cdmg;
	public Integer spd;
	public Integer hp;
	public Integer atk;
	public Integer crate;
	public String id;

}
