package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class MonsterConfigBean {

	public String monsterId;
	public String buildId;
	public String userId;
	public Integer requiredDef;
	public Integer notationSpd;
	public Integer requiredAcc;
	public Integer notationHp;
	public String runeStat2Type;
	public Integer requiredCrate;
	public String runeStat4Type;
	public String id;
	public Integer requiredAtk;
	public Integer requiredCdmg;
	public Integer notationCdmg;
	public Integer notationAcc;
	public Integer notationDef;
	public String set3;
	public Integer requiredRes;
	public String set2;
	public Boolean brokenSet;
	public Integer requiredSpd;
	public String runeStat6Type;
	public Integer requiredHp;
	public Integer notationCrate;
	public Integer notationAtk;
	public String set1;
	public Integer orderAtk;
	public Integer notationRes;

}
