package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class MonsterBean {

	public String userId;
	public Integer acc;
	public Integer res;
	public Integer lvl;
	public String role;
	public Integer star;
	public Boolean isAwaked;
	public Integer def;
	public Integer spd;
	public Integer hp;
	public Integer crate;
	public String elemType;
	public Boolean isLock;
	public Integer cdmg;
	public String name;
	public Integer xp;
	public Integer atk;
	public Long unitId;
	public String id;

}
