package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class RuneBean {

	public String monsterId;
	public String userId;
	public Integer lvl;
	public String set;
	public String stat4Type;
	public Integer star;
	public String stat2Type;
	public Integer statSub;
	public Integer statMain;
	public Integer stat4;
	public String stat3Type;
	public Integer stat2;
	public String pos;
	public Integer stat3;
	public String statSubType;
	public Integer stat1;
	public String stat1Type;
	public String statMainType;
	public String id;
	public Long uniqueId;

}
