package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class TeamResultBean {

	public String buildResultId;
	public String userId;
	public Double eval;
	public String id;

}
