package org.ap.summonerwar.bean;

import java.util.List;

/* This class was auto-generated by the JavaWriter */
public class UserBean {

	public List<Integer> lastImport;
	public String id;
	public String username;
	public String password;
	public String email;

}
