package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class UserBean {

	public Long lastImport;
	public String id;
	public String username;
	public String password;

}
