package org.ap.summonerwar.bean;

/* This class was auto-generated by the JavaWriter */
public class UserCredentialsBean {

	public String mail;
	public String id;
	public String username;
	public String password;

}
