import AppHelper from 'helpers/AppHelper'
import AuthHelper from 'helpers/AuthHelper'

import MonsterConfigHelper from 'helpers/MonsterConfigHelper'

import {Utils, BaseData}  from 'ap-react-bootstrap'


/* This class was auto-generated by the JavaScriptWriter */
class MonsterConfigListData extends BaseData {

	register(obj) {
		super.register(obj)

		this.obj.onClickAddMonsterConfig = this.onClickAddMonsterConfig.bind(this)
		this.obj.onClickDeleteMonsterConfig = this.onClickDeleteMonsterConfig.bind(this)

       	this.obj.state = {
            monstersConfig: []
        }

        AppHelper.register('/currentBuild', this, this._onBuildChange.bind(this));

	}

	_onBuildChange() {
		let build = AppHelper.getData('/currentBuild')

        MonsterConfigHelper.getBuildMonstersconfig(build.id).
        then(function() {
        	this.monstersConfig = {}
        	let storeMonstersConfig = MonsterConfigHelper.getData()
        	for(let key in storeMonstersConfig)
        		this.monstersConfig[key] = Utils.clone(storeMonstersConfig[key])
			AppHelper.put('/currentMonstersConfig', this.monstersConfig).
			then( function() {
				this.setState({monstersConfig: this.monstersConfig})
			}.bind(this))
        }.bind(this))
	}

	onClickAddMonsterConfig() {
		let monstersConfig = this.getState('monstersConfig')
		let monsterConfig = {id: String(new Date().getTime())}

		monstersConfig[monsterConfig.id] = monsterConfig
		AppHelper.put('/currentMonstersConfig', monstersConfig).
		then( function() {
			this.setState({monstersConfig: monstersConfig})
		}.bind(this))
	}

	onClickDeleteMonsterConfig(monsterConfig) {
		let monstersConfig = this.getState('monstersConfig')
		delete(monstersConfig[monsterConfig.id])
		this.setState({monstersConfig: monstersConfig})
	}

	unregister() {
		AppHelper.unregister(this)
	}
}
var MonsterConfigListObj = new MonsterConfigListData();
export default MonsterConfigListObj;
