import React from 'react'
import MonsterConfigListData from 'components-lib/monsterConfigList/MonsterConfigListData'
import MonsterConfig from 'components-lib/monsterConfig/MonsterConfig'
import SWPanel from 'components-lib/ui/SWPanel'

import {Utils}  from 'ap-react-bootstrap'

import './MonsterConfigList.scss';

/* This class was auto-generated by the JavaScriptWriter */
class MonsterConfigList extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		MonsterConfigListData.register(this)
	}

	componentWillUnmount() {
		MonsterConfigListData.unregister()
	}

	_buildMonstersConfig(monsterConfig) {
		return (<MonsterConfig key={monsterConfig.id} monsterConfig={monsterConfig} onClick={this.onClickDeleteMonsterConfig}/>)
	}

	render() {
		return (
			<div className={"sm-builds-monsters " + (this.state.haveBuild ? "" : "sm-hide")} size="lg">
				<div className="sm-builds-monsters-scroll">
					{Utils.map(this.state.monstersConfig, this._buildMonstersConfig.bind(this))}
					<div className={"sm-builds-monster-add1 " + (Object.keys(this.state.monstersConfig).length === 0 ? "sm-builds-monster-empty" : "")}>
						<i className="glyphicon glyphicon-plus-sign sm-builds-monster-add" onClick={this.onClickAddMonsterConfig.bind(this)}></i>
						<span>Add New<br/>Monster Config</span>
					</div>
				</div>
			</div>
		);
	}

}
export default MonsterConfigList;
