package org.ap.summonerwar.rest.filter;

import javax.ws.rs.WebApplicationException;
import javax.ws.rs.container.ContainerRequestContext;
import javax.ws.rs.container.ContainerRequestFilter;
import javax.ws.rs.container.PreMatching;
import org.ap.web.rest.security.*;
import org.ap.web.internal.APWebException;
import javax.ws.rs.core.Response.Status;
import org.ap.summonerwar.storage.ApauthCollection;
import org.ap.summonerwar.storage.ApauthData;

/* This class was auto-generated by the JavaWriter */
@PreMatching
public class AuthorizationRequestFilter implements ContainerRequestFilter {

	public static final String HEADER = "Authorization";

	public AuthorizationRequestFilter() {
	}

	@Override
	public void filter(ContainerRequestContext requestContext) throws WebApplicationException {
		if (requestContext.getMethod().equals("OPTIONS")) return;
		String header = requestContext.getHeaderString(HEADER);
		if (header == null) {
			throw new WebApplicationException(Status.UNAUTHORIZED);
		} else {
			try {
				String[] credentials = Encoder.decodeBasicAuth(header);
				if (credentials == null || credentials.length != 2) {
					throw new WebApplicationException(Status.UNAUTHORIZED);
				}
				ApauthData dataAuth = ApauthCollection.getByUsername(credentials[0]);
				if (dataAuth == null || !credentials[1].equals(dataAuth.getPassword())) {
					throw new WebApplicationException(Status.UNAUTHORIZED);
				}
				
				String[] roles = new String[0];
				requestContext.setSecurityContext(new APSecurityContext(dataAuth.getUsername(), roles));
			} catch (APWebException e) {
				throw new WebApplicationException(Status.UNAUTHORIZED);
			}
		}
	}

}
