import React from 'react';
import RunesData from 'components/runes/RunesData';
import Rune from 'components/lib/rune/Rune';
import {Utils}  from 'ap-react-bootstrap';
import './Runes.scss';

/* This class was auto-generated by the JavaScriptWriter */
class Runes extends React.Component {

	constructor(props) {
		super(props);
	}

	componentWillMount() {
		RunesData.register(this)
	}

	componentWillUnmount() {
		RunesData.unregister()
	}

	buildRune(rune) {
		return (<Rune key={rune.id} rune={rune}/>)
	}

	buildType(type) {
		return (
			<div className="sm-rune-type">
				<img key={type.name} className="sm-rune-type-image sm-rune-active" src={"assets/images/runes/Rune-" + type.name + ".png"}/>
			</div>
		)
	}

	render() {
		return (
			<div className='ap-runes'>
				<div className="row">
					<div className="col-xs-8">
						<div className="sm-runes-lists">
							<div className="sm-runes-list">
								<h3 className="sm-runes-list-title">All</h3>
								<div className="sm-runes">
									{Utils.map(this.state.runes, this.buildRune)}
								</div>
							</div>
						</div>
					</div>
					<div className="col-xs-4">
						<div className="sm-sheet">
							<ul className="sm-runes-filters">
								<li>
									<label className="sm-label">Grade</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Atk</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Def</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Spd</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
							</ul>
							<ul className="sm-runes-filters">
								<li>
									<label className="sm-label">Crate</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Cdmg</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Res</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
								<li>
									<label className="sm-label">Acc</label>
									<input className="sm-checkbox" type="checkbox"/>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div className="row">
					<div className="col-xs-12">
						<div className="sm-runes-types">
							{Utils.map(this.state.types, this.buildType)}
						</div>
					</div>
				</div>
			</div>
		);
	}

}
export default Runes;
