import AppHelper from 'helpers/AppHelper';
import AuthHelper from 'helpers/AuthHelper';
import { Dispatcher } from 'ap-flux';

/* This class was auto-generated by the JavaScriptWriter */
class LoginData {

	register(obj) {
		this.obj = obj

		this.mail = ""
		this.password = ""

		this.init();
	}

	unregister() {
	}

	onClick() {
		if(this.obj.props.onClick)
			this.obj.props.onClick()
	}

	onSubmit() {
		AuthHelper.getAuth({ username: this.mail, password: this.password }).
		then(AppHelper.navigate.bind(AppHelper, 'profile'))
	}

	onChange(id, event) {
		if (id == 'mail') {
			this.mail = event.target.value;
	    	this.obj.setState({mail: this.mail})
		} else {
			this.password = event.target.value;
	    	this.obj.setState({password: this.password});
		}
	 }

	init() {
		this.onChange = this.onChange.bind(this)
		this.onSubmit = this.onSubmit.bind(this)
		this.onClick = this.onClick.bind(this)

		this.obj.setState({
			mail: this.mail, 
			password: this.password, 
			onChange: this.onChange,
			onSubmit: this.onSubmit,
			onClick: this.onClick
		})
	}
}
var LoginObj = new LoginData();
export default LoginObj;
